/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author rdsbl
 */
public class VPanelMonitores extends javax.swing.JPanel {

    /**
     * Creates new form VistaGestionMonitores
     */
    public VPanelMonitores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNuevoMonitor = new javax.swing.JButton();
        jButtonBajaMonitor = new javax.swing.JButton();
        jButtonActualizacionMonitor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonitor = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1050, 427));

        jButtonNuevoMonitor.setText("Nuevo monitor");
        jButtonNuevoMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoMonitorActionPerformed(evt);
            }
        });

        jButtonBajaMonitor.setText("Baja de monitor");
        jButtonBajaMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaMonitorActionPerformed(evt);
            }
        });

        jButtonActualizacionMonitor.setText("Actualizacion de monitor");
        jButtonActualizacionMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizacionMonitorActionPerformed(evt);
            }
        });

        jTableMonitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMonitor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevoMonitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBajaMonitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonActualizacionMonitor))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoMonitor)
                    .addComponent(jButtonBajaMonitor)
                    .addComponent(jButtonActualizacionMonitor))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizacionMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizacionMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizacionMonitorActionPerformed

    private void jButtonBajaMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBajaMonitorActionPerformed

    private void jButtonNuevoMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoMonitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizacionMonitor;
    public javax.swing.JButton jButtonBajaMonitor;
    public javax.swing.JButton jButtonNuevoMonitor;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMonitor;
    // End of variables declaration//GEN-END:variables
}
