/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author rdsbl
 */
public class VPanelSocios extends javax.swing.JPanel {

    /**
     * Creates new form VistaGestionSocios
     */
    public VPanelSocios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNuevoSocio = new javax.swing.JButton();
        jButtonBajaSocio = new javax.swing.JButton();
        jButtonActualizacionSocio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocio = new javax.swing.JTable();
        jButtonVaciarTabla = new javax.swing.JButton();
        jButtonCargarTodos = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(962, 360));

        jButtonNuevoSocio.setText("Nuevo socio");

        jButtonBajaSocio.setText("Baja de socio");
        jButtonBajaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaSocioActionPerformed(evt);
            }
        });

        jButtonActualizacionSocio.setText("Actualizacion de socio");
        jButtonActualizacionSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizacionSocioActionPerformed(evt);
            }
        });

        jTableSocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSocio);

        jButtonVaciarTabla.setText("Vaciar tabla");
        jButtonVaciarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVaciarTablaActionPerformed(evt);
            }
        });

        jButtonCargarTodos.setText("Cargar todos los socios");
        jButtonCargarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarTodosActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar socio");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevoSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBajaSocio)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonActualizacionSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCargarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVaciarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoSocio)
                    .addComponent(jButtonBajaSocio)
                    .addComponent(jButtonActualizacionSocio)
                    .addComponent(jButtonCargarTodos)
                    .addComponent(jButtonVaciarTabla)
                    .addComponent(jButtonBuscar))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBajaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBajaSocioActionPerformed

    private void jButtonActualizacionSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizacionSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizacionSocioActionPerformed

    private void jButtonVaciarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaciarTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVaciarTablaActionPerformed

    private void jButtonCargarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCargarTodosActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizacionSocio;
    public javax.swing.JButton jButtonBajaSocio;
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonCargarTodos;
    public javax.swing.JButton jButtonNuevoSocio;
    public javax.swing.JButton jButtonVaciarTabla;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSocio;
    // End of variables declaration//GEN-END:variables
}
